language: java
install: true

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk8
  - openjdk7
deploy:
  skip_cleanup: true

branches:
  only:
  - master

matrix:
  fast_finish: true

notifications:
  on_success: never
  on_failure: always