#
#   Credit to github/martjin-heil for the request.
#   This is the default config for Lukkit.
#

# Leave this line alone please, I'm begging you, just don't do it!
cfg-version: 2

# Should I check for updates and let you know?
update-checker: true

# Whether or not /lukkit run can be used.
can-run-code: true
