name: Lukkit
main: unwrittenfun.bukkit.lukkit.Lukkit
version: 0.2.0
commands:
  lukkit:
    description: The main command for Lukkit
    usage: /<command> [sub-command]
    permission: lukkit.lukkit
    permission-message: You don't have permission to do that.
permissions:
  lukkit.lukkit:
    description: Give access to the lukkit command.
    default: op